export * from "./Back";
export * from "./Drag";
export * from "./Edit";
export * from "./Home";
export * from "./Menu";
export * from "./Search";
export * from "./Tick";
export * from "./Trash";
export * from "./X";
